### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by ccaulk** [jccastel/Castelli2275#1]
When putting in different times for the third and fourth variable it seems to return the same values for different numbers 90 90 returns the same as 90 3. I don't know what these numbers represent so a description in the readme would be helpful such as I think the first number is the time it runs and the second is dt or the velocity of the traveling radio. Also the program crashes in the second number is much higher than the first. I don't know if the numbers are suppose to only be 90 and 3 or can change.

**Comment by jccastel** [comment]
Thanks, caleb. Updated the readme, and fixing the input issue with a default dt = sim time/10. Per your comment above <90 3> input should produce the same output as <90 90> (both run a hypothetical 90 second simulation) since there is no noise / randomness to the motion.
